server:
  port: ${PORT:8084}

spring:
  application:
    name: frontend-service
  web:
    resources:
      static-locations: classpath:/static/

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: ${HOSTNAME:localhost}
    prefer-ip-address: true
